[package]
name = "origlang-intro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
derive_more = "0.99.17"
tap = "1.0.1"
thiserror = "1.0.37"
