print "99 bottles of beer on the wall, 99 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "98 bottles of beer on the wall, 98 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "97 bottles of beer on the wall, 97 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "96 bottles of beer on the wall, 96 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "95 bottles of beer on the wall, 95 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "94 bottles of beer on the wall, 94 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "93 bottles of beer on the wall, 93 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "92 bottles of beer on the wall, 92 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "91 bottles of beer on the wall, 91 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "90 bottles of beer on the wall, 90 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "89 bottles of beer on the wall, 89 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "88 bottles of beer on the wall, 88 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "87 bottles of beer on the wall, 87 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "86 bottles of beer on the wall, 86 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "85 bottles of beer on the wall, 85 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "84 bottles of beer on the wall, 84 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "83 bottles of beer on the wall, 83 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "82 bottles of beer on the wall, 82 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "81 bottles of beer on the wall, 81 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "80 bottles of beer on the wall, 80 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "79 bottles of beer on the wall, 79 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "78 bottles of beer on the wall, 78 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "77 bottles of beer on the wall, 77 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "76 bottles of beer on the wall, 76 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "75 bottles of beer on the wall, 75 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "74 bottles of beer on the wall, 74 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "73 bottles of beer on the wall, 73 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "72 bottles of beer on the wall, 72 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "71 bottles of beer on the wall, 71 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "70 bottles of beer on the wall, 70 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "69 bottles of beer on the wall, 69 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "68 bottles of beer on the wall, 68 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "67 bottles of beer on the wall, 67 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "66 bottles of beer on the wall, 66 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "65 bottles of beer on the wall, 65 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "64 bottles of beer on the wall, 64 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "63 bottles of beer on the wall, 63 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "62 bottles of beer on the wall, 62 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "61 bottles of beer on the wall, 61 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "60 bottles of beer on the wall, 60 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "59 bottles of beer on the wall, 59 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "58 bottles of beer on the wall, 58 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "57 bottles of beer on the wall, 57 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "56 bottles of beer on the wall, 56 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "55 bottles of beer on the wall, 55 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "54 bottles of beer on the wall, 54 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "53 bottles of beer on the wall, 53 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "52 bottles of beer on the wall, 52 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "51 bottles of beer on the wall, 51 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "50 bottles of beer on the wall, 50 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "49 bottles of beer on the wall, 49 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "48 bottles of beer on the wall, 48 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "47 bottles of beer on the wall, 47 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "46 bottles of beer on the wall, 46 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "45 bottles of beer on the wall, 45 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "44 bottles of beer on the wall, 44 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "43 bottles of beer on the wall, 43 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "42 bottles of beer on the wall, 42 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "41 bottles of beer on the wall, 41 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "40 bottles of beer on the wall, 40 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "39 bottles of beer on the wall, 39 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "38 bottles of beer on the wall, 38 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "37 bottles of beer on the wall, 37 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "36 bottles of beer on the wall, 36 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "35 bottles of beer on the wall, 35 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "34 bottles of beer on the wall, 34 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "33 bottles of beer on the wall, 33 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "32 bottles of beer on the wall, 32 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "31 bottles of beer on the wall, 31 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "30 bottles of beer on the wall, 30 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "29 bottles of beer on the wall, 29 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "28 bottles of beer on the wall, 28 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "27 bottles of beer on the wall, 27 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "26 bottles of beer on the wall, 26 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "25 bottles of beer on the wall, 25 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "24 bottles of beer on the wall, 24 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "23 bottles of beer on the wall, 23 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "22 bottles of beer on the wall, 22 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "21 bottles of beer on the wall, 21 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "20 bottles of beer on the wall, 20 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "19 bottles of beer on the wall, 19 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "18 bottles of beer on the wall, 18 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "17 bottles of beer on the wall, 17 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "16 bottles of beer on the wall, 16 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "15 bottles of beer on the wall, 15 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "14 bottles of beer on the wall, 14 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "13 bottles of beer on the wall, 13 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "12 bottles of beer on the wall, 12 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "11 bottles of beer on the wall, 11 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "10 bottles of beer on the wall, 10 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "9 bottles of beer on the wall, 9 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "8 bottles of beer on the wall, 8 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "7 bottles of beer on the wall, 7 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "6 bottles of beer on the wall, 6 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "5 bottles of beer on the wall, 5 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "4 bottles of beer on the wall, 4 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "3 bottles of beer on the wall, 3 bottles of beer."
print "Take one down and pass it around, bottles of beer on the wall."
print "2 bottles of beer on the wall, 2 bottles of beer."
print "Take one down and pass it around, bottle of beer on the wall."
print "1 bottle of beer on the wall, 1 bottle of beer."
print "Take one down and pass it around, no more bottles of beer on the wall."
print "No more bottles of beer on the wall, no more bottles of beer."
print "Go to the store and buy some more, 99 bottles of beer on the wall."
