[package]
name = "origlang-lexer"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
log = "0.4.21"
thiserror = "2.0.0"
origlang-ast = { path = "../origlang-ast" }
origlang-source-span = { path = "../origlang-source-span" }
