name: validate-renovate-custom-managers.yml
on:
  pull_request:
    paths:
      - renovate.json
      - .github/workflows/validate-renovate-custom-managers.yml
      - .github/workflows/shell_scripts/validate-renovate-custom-managers.sh

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: check
        run: ./.github/workflows/shell_scripts/validate-renovate-custom-managers.sh
